### ISSUE TITLE
The vercel deployment is not working

### ISSUE THREAD

**Issue by alpha951** [adafycheng/music-album#1] opened 2022-07-09 12:21 UTC
Hey, I want to deploy my node express js based application on vercel but it's not working according to your tutorial and your application  is not working too.

**Comment by adafycheng** [comment] 2022-07-22 10:44
Hi.  Thanks for the comment.

Sorry that I was busy in past few weeks.

The root cause why my application not running was that ')' was wrongly added in line 43 of app.js.  The bug was fixed and the problem was now resolved.  The application should now work in Vercel.

For your application, can you tell me more on your case?

**Comment by alpha951** [comment] 2022-07-22 12:07
You can visit my app at https://github.com/alpha951/Secret1 . If possible, please share some proper documentation to deploy a node js app on Vercel which requires npm modules to be installed on the server. Currently, my deployment is showing this error https://secret1.vercel.app/ .
And also do I need to write some command on Vercel to install the required npm module or it will detect them automatically from package.json .

**Comment by adafycheng** [comment] 2022-07-22 12:27
Strange that I cannot find the package.json file in your committed project.

**Comment by adafycheng** [comment] 2022-07-22 12:43
You may refer to another blog post (https://blog.adafycheng.dev/write-express-server-to-send-email) for creating the package.json file for your project.

I think the root cause is the missing `package.json` file for including the packages.

**Closed as completed** 2022-07-25 10:54 UTC

**Comment by alpha951** [comment] 2022-10-11 06:56
Actually I had deleted the package.json file since one of tutorial told me
to do so ( actually some YouTube comments) , before that I was having
package.json and the vercel app was not working.
Please tell me that do I need to write npm install command and override on
in deployment settings on vercel.
Thanks for your help.
